## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('chord-run', ['chord-ipv4'])
    obj.source = 'chord-run.cc'
    obj.env.append_value('LINKFLAGS','-lcrypto')
